name: Build Chart.js and generate minified file

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build Chart.js
        run: npm run build

      - name: Minify chart.umd.js
        run: |
          npm install -g terser
          terser dist/chart.umd.js -o dist/chart.umd.min.js -c -m

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chartjs-dist
          path: dist/
